kind: ConfigMap
apiVersion: v1
metadata:
  name: mongo-config-map
  namespace: default
data:
  init_mongo.js: | 
    db.auth('admin', 'admin')
    db = db.getSiblingDB('demo_db')
    db.createUser({
      user: 'boki',
      pwd: 'boki',
      roles: [{ role: 'dbOwner', db: 'demo_db' }],
    })

# mongosh demo_db -u boki --authenticationDatabase demo_db -p boki
