name: Create  a comment on new issues

on:
    issues:
        types: [opened] #like "opened" issue

jobs:
    comment-with-action:
    # action fetcha automatski env varijable, pa zato ih
    # ne trebamo tu definirati
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
        # znaci neka koristimo community action koji ce sam
        # generirati neki dummy komentar
          - name: "dump github context"
            run: echo '${{ toJSON(github.event) }}' | jq
            shell: bash
          - name: Create comment
            uses: peter-evans/create-or-update-comment@v3
            with:
              issue-number: ${{ github.event.issue.number }}
              body: |
                This is a multi-line test comment
                - With GitHub **Markdown** :sparkles:
                - Created by [create-or-update-comment][1]

                [1]: https://github.com/peter-evans/create-or-update-comment
              reactions: '+1'
    
    comment-with-api:
      permissions: write-all
      runs-on: ubuntu-latest
      steps:
        - name: Create comment with GithubAPI
        # we dont need to write curl, github has its own api
          run: | 
            gh api -X POST \
              http://api.github.com/repo/$(ORGANIZATION)/$(REPOSITORY)/issues/$(ISSUE_NUMBER)/comments \
              -f body= '
              Comment from API call not actions
              '
          env:
          # potrebna env varijabla za api call-ove
          # samo je dostupan for duration of a workflow run
          # za novi workflow se promijeni
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ORGANIZATION: ${{ secrets.event.organization.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}

